---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create plugins neutron dir
  file:
    path: "{{ item.path | default(omit) }}"
    state: "directory"
    owner: "{{ item.owner|default(neutron_system_user_name) }}"
    group: "{{ item.group|default(neutron_system_group_name) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - path: "{{ neutron_conf_dir }}/plugins"
      mode: "0750"
    - path: "{{ neutron_conf_dir }}/plugins/{{ neutron_plugin_type.split('.')[0] }}"
      mode: "0750"
    - path: "{{ neutron_conf_dir }}/rootwrap.d"
      owner: "root"
      group: "root"

# NOTE(cloudnull): This task is required to copy rootwrap filters that we need
#                  and neutron does not provide by default.
- name: Copy extra neutron rootwrap filters
  copy:
    src: "{{ item }}"
    dest: "{{ neutron_conf_dir }}/rootwrap.d/"
    owner: "root"
    group: "root"
  with_fileglob:
    - rootwrap.d/*
  notify:
    - Restart neutron services

- name: Copy common neutron config
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "{{ item.group|default(neutron_system_group_name) }}"
    mode: "0640"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "neutron.conf.j2"
      dest: "{{ neutron_conf_dir }}/neutron.conf"
      config_overrides: "{{ neutron_neutron_conf_overrides }}"
      config_type: "ini"
    - src: "{{ neutron_plugins[neutron_plugin_type].plugin_ini }}.j2"
      dest: "{{ neutron_conf_dir }}/{{ neutron_plugins[neutron_plugin_type].plugin_ini }}"
      config_overrides: "{{ neutron_plugins[neutron_plugin_type].plugin_conf_ini_overrides }}"
      config_type: "ini"
  notify:
    - Restart neutron services

- name: Place api-paste.ini to the correct path in RedHat
  file:
    src: "/usr/share/neutron/api-paste.ini"
    dest: "{{ neutron_conf_dir }}/api-paste.ini"
    owner: "root"
    group: "{{ neutron_system_group_name }}"
    mode: "0640"
    state: link
  when: neutron_install_method == 'distro' and ansible_os_family == 'RedHat'

- name: Preserve original configuration file(s)
  command: "cp {{ item.target_f }} {{ item.target_f }}.original"
  args:
    creates: "{{ item.target_f }}.original"
  with_items: "{{ neutron_core_files }}"

- name: Fetch override files
  fetch:
    src: "{{ item.target_f }}.original"
    dest: "{{ item.tmp_f }}"
    flat: yes
  changed_when: false
  with_items: "{{ neutron_core_files }}"
  run_once: true

- name: Copy common neutron config
  config_template:
    src: "{{ item.tmp_f }}"
    dest: "{{ item.target_f }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default(neutron_system_group_name) }}"
    mode: "{{ item.mode | default('0640') }}"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items: "{{ neutron_core_files }}"
  notify:
    - Restart neutron services

- name: Cleanup fetched temp files
  file:
    path: "{{ item.tmp_f }}"
    state: absent
  changed_when: false
  delegate_to: localhost
  with_items: "{{ neutron_core_files }}"

# NOTE(cloudnull): This will ensure strong permissions on all rootwrap files.
- name: Set rootwrap.d permissions
  file:
    path: "{{ neutron_conf_dir }}/rootwrap.d"
    owner: "root"
    group: "root"
    mode: "0640"
    recurse: true

- name: Copy neutron ml2 plugin config
  config_template:
    src: "{{ neutron_plugins[item].plugin_ini }}.j2"
    dest: "{{ neutron_conf_dir }}/{{ neutron_plugins[item].plugin_ini }}"
    owner: "root"
    group: "{{ neutron_system_group_name }}"
    mode: "0640"
    config_overrides: "{{ neutron_plugins[item].plugin_conf_ini_overrides }}"
    config_type: "ini"
  with_items: "{{ neutron_plugin_types }}"

- name: Generate neutron dnsmasq Config
  template:
    src: "dnsmasq-neutron.conf.j2"
    dest: "{{ neutron_conf_dir }}/dnsmasq-neutron.conf"
    owner: "root"
    group: "{{ neutron_system_group_name }}"
    mode: "0640"
  notify:
    - Restart neutron services
  when:
    - neutron_services['neutron-dhcp-agent']['group'] in group_names

- name: Generate neutron agent only Config
  config_template:
    src: "{{ item.service_conf }}.j2"
    dest: "{{ item.service_conf_path }}/{{ item.service_conf }}"
    owner: "root"
    group: "{{ neutron_system_group_name }}"
    mode: "0640"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items: "{{ filtered_neutron_services }}"
  notify:
    - Restart neutron services
  when:
    - "'service_conf_path' in item"
    - "'service_conf' in item"

- name: Generate neutron bgpvpn networking configuration
  template:
    src: "networking_bgpvpn.conf.j2"
    dest: "{{ neutron_conf_dir }}/networking_bgpvpn.conf"
    owner: "root"
    group: "{{ neutron_system_group_name }}"
    mode: "0640"
  notify:
    - Restart neutron services
  when:
    - "'bgpvpn' in neutron_plugin_base"

# NOTE: Remove this in S
# This option has been removed with the implementation of networkd within the
# host and container. Additionally the execution of this script is now
# controlled by a systemd oneshot service so the legacy configs are no longer
# needed.
- name: Remove checksum fix scripts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ neutron_checksum_script }}"
    - "/usr/local/bin/post-up-metadata-checksum"
