---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  notify:
    - Restart neutron services

- name: Restart neutron services
  service:
    name: "{{ item.service_name }}"
    state: restarted
    pattern: "{{ item.service_name }}"
  with_items: "{{ filtered_neutron_services }}"
  notify:
    - Run ns-metadata-proxy process cleanup
    - Perform a DB contract

# NOTE(cloudnull):
# When installing or upgrading it is possible that an old metadata proxy process will not
#  be restarted by the metadata agent when a version changes. To fix it the ns-metadata
#  proxy pids are killed if they're not running the current tag. Once the old processeses
#  are removed the metadata agent will respawn the missing process within 60 seconds using
#  the correct code.
- name: Run ns-metadata-proxy process cleanup
  shell: |
    for ns_pid in $(pgrep neutron-ns-meta); do
      echo $(readlink -f "/proc/$ns_pid/exe") | grep -qv "{{ neutron_venv_tag }}"
      if [ $? -eq 0 ]; then
        if kill -9 "$ns_pid"; then
          logger -s "old metadata proxy pid found and has been cleaned up on: \"$ns_pid\""
        fi
      fi
    done
  when: "'neutron-metadata-agent' in (filtered_neutron_services | map(attribute='service_key') | list)"

- name: Perform a DB contract
  command: "{{ neutron_bin }}/neutron-db-manage upgrade --contract"
  become: yes
  become_user: "{{ neutron_system_user_name }}"
  when:
    - "ansible_local['openstack_ansible']['neutron']['need_db_contract'] | bool"
    - "inventory_hostname == groups[neutron_services['neutron-server']['group']][0]"
