---
# Copyright 2017, Ericsson AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install OpenDaylight pip packages
  pip:
    name: "{{ neutron_optional_opendaylight_pip_packages }}"
    state: "{{ neutron_pip_package_state }}"
    virtualenv: "{{ neutron_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ neutron_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - opendaylight-install
    - opendaylight-pip-packages

- name: Ensure Open vSwitch service is started and enabled
  service:
    name: "{{ neutron_ovs_service_name }}"
    state: started
    enabled: yes

- name: Retrieve current OvS manager
  command: ovs-vsctl get-manager
  register: ovs_manager
  changed_when: False

- name: Set ODL as OvS manager
  command: ovs-vsctl set-manager tcp:{{ odl_ip }}:6640
  when: ovs_manager.stdout == ""

- name: Configure hosts for networking-odl, force kernel datapath
  command: "{{ neutron_bin }}/neutron-odl-ovs-hostconfig --noovs_dpdk"
  when: ovs_manager.stdout == ""

- name: Retrieve current OvS local ip
  command: ovs-vsctl get Open_vSwitch . other_config:local_ip
  ignore_errors: yes
  register: ovs_local_ip
  changed_when: False

- name: Set local ip for OpenvSwitch
  command: "ovs-vsctl set Open_vSwitch . other_config:local_ip={{ neutron_local_ip }}"
  when: ovs_local_ip.rc != 0
